# Load version number components.
include (${CMAKE_SOURCE_DIR}/Versions.cmake)

# Compute the version string
#MacOS must use semantic versioning for the Info.plist short string
set (MACOS_VERSION_SHORT ${WSJTX_VERSION_PATCH})

if (NOT WSJTX_VERSION_IS_RELEASE)
  set (WSJTX_VERSION_PATCH ${WSJTX_VERSION_PATCH}-NOT_FOR_RELEASE)
elseif (WSJTX_VERSION_IS_RELEASE)
  set (WSJTX_VERSION_PATCH ${WSJTX_VERSION_PATCH})
endif (NOT WSJTX_VERSION_IS_RELEASE)

set (wsjtx_VERSION ${WSJTX_VERSION_MAJOR}.${WSJTX_VERSION_MINOR}.${WSJTX_VERSION_PATCH})
set (wsjtx_SHORT_VERSION ${WSJTX_VERSION_MAJOR}.${WSJTX_VERSION_MINOR}.${MACOS_VERSION_SHORT})
